/**
 * Copyright 2026 Franja (Frank) Povazanj
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { canvasEn } from '../en/canvas'

/** French sketch-canvas catalog. */
export const canvasFr: Record<keyof typeof canvasEn, string> = {
  'canvas.target.drawingFeatures': 'Dessin d’entités', 'canvas.target.drawingLines': 'Dessin de lignes', 'canvas.target.drawingRegions': 'Dessin de régions', 'canvas.target.drawingConstruction': 'Dessin de construction',
  'canvas.legend.heading': 'Couleurs des entités', 'canvas.legend.collapseAria': 'Réduire la légende des couleurs d’entités', 'canvas.legend.collapseTitle': 'Réduire la légende', 'canvas.legend.subtract': 'Soustraire', 'canvas.legend.addFeature': 'Ajouter une entité', 'canvas.legend.regionInclude': 'Région incluse', 'canvas.legend.regionExclude': 'Région exclue', 'canvas.legend.importedModel': 'Modèle importé', 'canvas.legend.selected': 'Sélectionné',
  'canvas.overlap.title': 'Sélectionner une entité', 'canvas.overlap.dialogAria': 'Sélectionner une entité', 'canvas.overlap.listAria': 'Entités superposées', 'canvas.overlap.step.one': '{count} entité se superpose ici. Choisissez-la.', 'canvas.overlap.step.other': '{count} entités se superposent ici. Choisissez-en une.', 'canvas.overlap.moveLabel': 'Déplacer les contrôles de sélection d’entité', 'canvas.overlap.selectAria': 'Sélectionner {name}, {kind}', 'canvas.overlap.cancel': 'Annuler', 'canvas.overlap.kind.rect': 'Rectangle', 'canvas.overlap.kind.circle': 'Cercle', 'canvas.overlap.kind.ellipse': 'Ellipse', 'canvas.overlap.kind.polygon': 'Polygone', 'canvas.overlap.kind.spline': 'Spline', 'canvas.overlap.kind.composite': 'Chemin composite', 'canvas.overlap.kind.text': 'Texte', 'canvas.overlap.kind.stl': 'Modèle STL',
  'canvas.common.confirm': 'Confirmer', 'canvas.common.cancel': 'Annuler', 'canvas.common.apply': 'Appliquer', 'canvas.common.done': 'Terminé', 'canvas.common.finish': 'Terminer', 'canvas.common.undo': 'Annuler', 'canvas.common.next': 'Suivant', 'canvas.common.moveControls': 'Déplacer les contrôles du flux de travail',
  'canvas.field.width': 'Largeur', 'canvas.field.height': 'Hauteur', 'canvas.field.radius': 'Rayon', 'canvas.field.length': 'Longueur', 'canvas.field.angle': 'Angle', 'canvas.field.angleDeg': 'Angle °', 'canvas.field.distance': 'Distance', 'canvas.field.diameter': 'Diamètre', 'canvas.field.copies': 'Copies', 'canvas.field.scale': 'Échelle',
  'canvas.shape.rectangle': 'Rectangle', 'canvas.shape.circle': 'Cercle', 'canvas.shape.ellipse': 'Ellipse', 'canvas.shape.tab': 'Attache', 'canvas.shape.clamp': 'Bride', 'canvas.shape.polygon': 'Polygone', 'canvas.shape.spline': 'Spline', 'canvas.shape.slot': 'Lumière', 'canvas.shape.gear': 'Engrenage', 'canvas.shape.roundedRectangle': 'Rectangle arrondi', 'canvas.shape.chamferedRectangle': 'Rectangle chanfreiné', 'canvas.shape.composite': 'Composite',
  'canvas.composite.mode.line': 'Ligne', 'canvas.composite.mode.arc': 'Arc', 'canvas.composite.mode.spline': 'Spline',
  'canvas.creation.step.enterDimensions': 'Saisir les dimensions', 'canvas.creation.step.clickFirstPoint': 'Cliquez sur le premier point', 'canvas.creation.step.clickFirstCorner': 'Cliquez sur le premier coin', 'canvas.creation.step.clickCenterPoint': 'Cliquez sur le point central', 'canvas.creation.step.clickArcCurvature': 'Cliquez sur le point de courbure de l’arc', 'canvas.creation.step.addPoints': 'Ajouter des points {mode}', 'canvas.creation.step.addOneMore': 'Ajouter un point', 'canvas.creation.step.addPointsOrClose': 'Ajouter des points ou fermer', 'canvas.creation.step.setRadiusOrDimensions': 'Cliquez pour définir le rayon ou saisissez les dimensions', 'canvas.creation.step.setRadiiOrDimensions': 'Cliquez pour définir les rayons ou saisissez les dimensions', 'canvas.creation.step.setRadius': 'Cliquez pour définir le rayon', 'canvas.creation.step.setCornerOrDimensions': 'Cliquez sur le coin opposé ou saisissez les dimensions', 'canvas.creation.step.slotFirstEnd': 'Cliquez sur le centre de la première extrémité', 'canvas.creation.step.slotSecondEnd': 'Cliquez sur le centre de la seconde extrémité ou saisissez les dimensions', 'canvas.creation.step.slotSetWidth': 'Déplacez le curseur pour définir la largeur, puis cliquez pour valider', 'canvas.creation.step.gearSetRadius': 'Cliquez pour définir le rayon extérieur ou saisissez le rayon', 'canvas.creation.step.gearParams': 'Définir les paramètres de l’engrenage', 'canvas.creation.moveLabel': 'Déplacer les contrôles de création', 'canvas.creation.dimensionsButton': 'Dimensions', 'canvas.creation.radiusButton': 'Rayon', 'canvas.creation.widthButton': 'Largeur', 'canvas.creation.confirmGear': 'Confirmer',
  'canvas.placement.originTitle': 'Placer l’origine', 'canvas.placement.textTitle': 'Placer le texte', 'canvas.placement.originStep': 'Cliquez dans l’esquisse pour placer le X0 Y0 machine. Z reste manuel dans Propriétés.', 'canvas.placement.textStep': 'Touchez l’esquisse pour placer le texte.', 'canvas.placement.cancel': 'Annuler',
  'canvas.constraint.title': 'Contrainte', 'canvas.constraint.editTitle': 'Modifier la contrainte', 'canvas.constraint.step.pickAnchor': 'Choisir le point d’ancrage', 'canvas.constraint.step.pickReference': 'Choisir le point de référence', 'canvas.constraint.step.setDistance': 'Définir la distance', 'canvas.constraint.moveLabel': 'Déplacer les contrôles de modification de contrainte', 'canvas.constraint.apply': 'Appliquer', 'canvas.constraint.cancel': 'Annuler', 'canvas.constraint.confirm': 'Confirmer', 'canvas.constraint.summary.anchor': 'Touchez un point d’accrochage sur cette entité.', 'canvas.constraint.summary.reference': 'Touchez un point d’accrochage sur une autre entité.',
  'canvas.driving.title.resizeStock': 'Redimensionner le brut', 'canvas.driving.title.editDimension': 'Modifier la cote', 'canvas.driving.step.setValue': 'Définir la valeur', 'canvas.driving.moveLabel': 'Déplacer les contrôles de modification pilotée', 'canvas.driving.flipHeldPoint': 'Inverser le point maintenu', 'canvas.driving.apply': 'Appliquer', 'canvas.driving.cancel': 'Annuler', 'canvas.driving.holdingSide': 'Côté {side} maintenu', 'canvas.driving.heldSide.left': 'gauche', 'canvas.driving.heldSide.right': 'droit', 'canvas.driving.heldSide.top': 'haut', 'canvas.driving.heldSide.bottom': 'bas', 'canvas.driving.holdLabel.left': 'Maintenir à gauche', 'canvas.driving.holdLabel.right': 'Maintenir à droite', 'canvas.driving.holdLabel.top': 'Maintenir en haut', 'canvas.driving.holdLabel.bottom': 'Maintenir en bas', 'canvas.driving.holdLabel.start': 'Maintenir le début', 'canvas.driving.holdLabel.end': 'Maintenir la fin', 'canvas.driving.holdLabel.firstRay': 'Maintenir le premier rayon', 'canvas.driving.holdLabel.secondRay': 'Maintenir le second rayon',
  'canvas.offset.title': 'Décalage', 'canvas.offset.step.setDistance': 'Définir la distance', 'canvas.offset.step.previewDistance': 'Prévisualiser la distance', 'canvas.offset.moveLabel': 'Déplacer les contrôles de décalage', 'canvas.offset.confirm': 'Confirmer', 'canvas.offset.distanceButton': 'Distance', 'canvas.offset.cancel': 'Annuler', 'canvas.offset.summary': 'Déplacez à l’intérieur ou à l’extérieur de l’entité pour prévisualiser. Cliquez pour valider.',
  'canvas.join.title': 'Joindre', 'canvas.join.step.selectFeatures': 'Sélectionner les entités', 'canvas.join.moveLabel': 'Déplacer les contrôles de jonction', 'canvas.join.confirm': 'Confirmer', 'canvas.join.cancel': 'Annuler', 'canvas.join.keepOriginals': 'Conserver les originaux', 'canvas.join.summary.tooFew': 'Sélectionnez au moins deux entités fermées.', 'canvas.join.summary.count.one': '{count} entité fermée sélectionnée.', 'canvas.join.summary.count.other': '{count} entités fermées sélectionnées.',
  'canvas.cut.title': 'Découper', 'canvas.cut.step.selectCutters': 'Sélectionner les découpeurs', 'canvas.cut.step.selectTargets': 'Sélectionner les cibles', 'canvas.cut.moveLabel': 'Déplacer les contrôles de découpe', 'canvas.cut.next': 'Suivant', 'canvas.cut.confirm': 'Confirmer', 'canvas.cut.cancel': 'Annuler', 'canvas.cut.keepOriginals': 'Conserver les originaux', 'canvas.cut.summary.noCutters': 'Sélectionnez des entités à utiliser comme découpeurs.', 'canvas.cut.summary.cutters.one': '{count} découpeur sélectionné.', 'canvas.cut.summary.cutters.other': '{count} découpeurs sélectionnés.', 'canvas.cut.summary.cuttersLocked.one': '{count} découpeur verrouillé. Sélectionnez les entités cibles.', 'canvas.cut.summary.cuttersLocked.other': '{count} découpeurs verrouillés. Sélectionnez les entités cibles.', 'canvas.cut.summary.targets.one': '{count} cible sélectionnée.', 'canvas.cut.summary.targets.other': '{count} cibles sélectionnées.',
  'canvas.move.title.copy': 'Copier', 'canvas.move.title.move': 'Déplacer', 'canvas.move.step.setDistance': 'Définir la distance', 'canvas.move.step.selectFrom': 'Sélectionner le point de départ', 'canvas.move.step.selectTarget': 'Sélectionner le point cible', 'canvas.move.step.setCopyCount': 'Définir le nombre de copies', 'canvas.move.moveLabel': 'Déplacer les contrôles {mode}', 'canvas.move.confirm': 'Confirmer', 'canvas.move.cancel': 'Annuler', 'canvas.move.summary.selectTarget': 'Sélectionnez un point cible pour définir la direction et la distance par défaut.',
  'canvas.transform.title.resize': 'Redimensionner', 'canvas.transform.title.mirror': 'Symétrie', 'canvas.transform.title.rotate': 'Rotation', 'canvas.transform.step.setScale': 'Définir l’échelle', 'canvas.transform.step.setAngle': 'Définir l’angle', 'canvas.transform.step.setCopyCount': 'Définir le nombre de copies', 'canvas.transform.step.selectFirstReference': 'Sélectionner la première référence', 'canvas.transform.step.selectSecondReference': 'Sélectionner la seconde référence', 'canvas.transform.step.scaleToCommit': 'Mettre à l’échelle pour valider', 'canvas.transform.step.selectFirstLinePoint': 'Sélectionner le premier point de ligne', 'canvas.transform.step.selectSecondLinePoint': 'Sélectionner le second point de ligne', 'canvas.transform.step.selectOrigin': 'Sélectionner l’origine', 'canvas.transform.step.selectReferenceDirection': 'Sélectionner la direction de référence', 'canvas.transform.step.rotateToCommit': 'Faire pivoter pour valider', 'canvas.transform.moveLabel': 'Déplacer les contrôles {mode}', 'canvas.transform.confirm': 'Confirmer', 'canvas.transform.scaleButton': 'Échelle', 'canvas.transform.angleButton': 'Angle', 'canvas.transform.cancel': 'Annuler', 'canvas.transform.keepOriginals': 'Conserver les originaux', 'canvas.transform.summary.resize': 'Déplacez le long de la ligne de référence pour prévisualiser, puis cliquez pour valider.', 'canvas.transform.summary.mirror': 'Déplacez pour prévisualiser, puis cliquez sur le second point de symétrie.', 'canvas.transform.summary.rotateCopy': 'Déplacez pour prévisualiser la copie pivotée, puis cliquez pour définir l’angle.', 'canvas.transform.summary.rotate': 'Déplacez pour prévisualiser, puis cliquez pour valider.',
  'canvas.edit.title': 'Modifier', 'canvas.edit.step.enterDimensions': 'Saisir les dimensions', 'canvas.edit.step.enterRadius': 'Saisir le rayon', 'canvas.edit.step.enterDistance': 'Saisir la distance', 'canvas.edit.step.clickToAddPoints': 'Cliquez pour ajouter des points', 'canvas.edit.step.clickToDeletePoints': 'Cliquez pour supprimer des points', 'canvas.edit.step.clickToDeleteSegments': 'Cliquez pour supprimer des segments', 'canvas.edit.step.clickAnchorToSplit': 'Cliquez sur une ancre pour scinder', 'canvas.edit.step.filletCorner': 'Cliquez sur un coin', 'canvas.edit.step.filletSecond': 'Cliquez sur le second point ou saisissez le rayon', 'canvas.edit.step.chamferCorner': 'Cliquez sur un coin', 'canvas.edit.step.chamferSecond': 'Cliquez sur le second point ou saisissez la distance', 'canvas.edit.step.trimSubject': 'Cliquez sur la partie du segment à retirer', 'canvas.edit.step.trimReference': 'Cliquez sur le segment de coupe', 'canvas.edit.step.extendSubject': 'Cliquez près de l’extrémité ouverte à prolonger', 'canvas.edit.step.extendReference': 'Cliquez sur le segment cible à atteindre', 'canvas.edit.step.default': 'Faites glisser les nœuds ou cliquez sur les segments', 'canvas.edit.apply': 'Appliquer', 'canvas.edit.cancel': 'Annuler', 'canvas.edit.confirm': 'Confirmer', 'canvas.edit.dimensionButton': 'Cote', 'canvas.edit.radiusButton': 'Rayon', 'canvas.edit.distanceButton': 'Distance', 'canvas.edit.warning.selfIntersecting': 'Profil auto-intersectant', 'canvas.edit.warning.exceedsStock': 'Dépasse du brut',
  'canvas.dimension.title.aligned': 'Cote alignée', 'canvas.dimension.title.horizontal': 'Cote horizontale', 'canvas.dimension.title.vertical': 'Cote verticale', 'canvas.dimension.title.radius': 'Cote de rayon', 'canvas.dimension.title.diameter': 'Cote de diamètre', 'canvas.dimension.title.angle': 'Cote angulaire', 'canvas.dimension.step.radiusCenter': 'Cliquez sur le centre du cercle/de l’arc', 'canvas.dimension.step.radiusEdge': 'Cliquez sur un point du bord', 'canvas.dimension.step.angleVertex': 'Cliquez sur le sommet', 'canvas.dimension.step.angleFirstRay': 'Cliquez sur le point du premier rayon', 'canvas.dimension.step.angleSecondRay': 'Cliquez sur le point du second rayon', 'canvas.dimension.step.clickToPlace': 'Cliquez pour placer', 'canvas.dimension.step.firstPoint': 'Cliquez sur le premier point', 'canvas.dimension.step.secondPoint': 'Cliquez sur le second point', 'canvas.dimension.step.setOffset': 'Cliquez pour définir le décalage', 'canvas.dimension.addCancel': 'Annuler', 'canvas.dimension.addSummary': 'Cliquez sur des points pour ancrer la cote à la géométrie. Échap pour annuler.', 'canvas.dimension.deleteTitle': 'Supprimer la cote', 'canvas.dimension.deleteStep': 'Cliquez sur une cote à supprimer', 'canvas.dimension.deleteDone': 'Terminé', 'canvas.dimension.deleteSummary': 'Cliquez sur chaque cote à retirer. Échap ou Terminé pour finir.',
  'canvas.tape.title': 'Mètre ruban', 'canvas.tape.step.first': 'Cliquez sur le premier point', 'canvas.tape.step.second': 'Cliquez sur le second point', 'canvas.tape.done': 'Terminé', 'canvas.tape.summary': 'S’accroche à la géométrie. La mesure reste jusqu’au prochain clic — Échap ou Terminé pour quitter.',
  'canvas.paste.title': 'Coller les entités', 'canvas.paste.step': 'Cliquez dans l’esquisse pour placer', 'canvas.paste.cancel': 'Annuler', 'canvas.paste.summary': 'Déplacez le pointeur pour prévisualiser la position de collage.',
  'canvas.gear.summary': 'Rayon extérieur {length}', 'canvas.gear.toothCount': 'Nombre de dents', 'canvas.gear.wholeDepth': 'Hauteur totale', 'canvas.gear.flankProfile': 'Profil de flanc de dent', 'canvas.gear.pressureAngle': 'Angle de pression', 'canvas.gear.rootForm': 'Forme du pied', 'canvas.gear.rootFilletRadius': 'Rayon de congé de pied', 'canvas.gear.crestForm': 'Forme de tête', 'canvas.gear.crestRadius': 'Rayon de tête', 'canvas.gear.boreDiameter': 'Diamètre d’alésage', 'canvas.gear.flank.involute': 'Développante', 'canvas.gear.flank.straight': 'Flanc droit', 'canvas.gear.root.rounded': 'Congé de pied arrondi', 'canvas.gear.root.flat': 'Pied plat', 'canvas.gear.root.sharp': 'Pied vif', 'canvas.gear.crest.flat': 'Tête plate', 'canvas.gear.crest.rounded': 'Tête arrondie',
  'canvas.gear.ref.teeth': 'Référence du nombre de dents', 'canvas.gear.ref.wholeDepth': 'Référence de hauteur totale', 'canvas.gear.ref.flankProfile': 'Référence du profil de flanc', 'canvas.gear.ref.pressureAngle': 'Référence de l’angle de pression', 'canvas.gear.ref.rootForm': 'Référence de forme du pied', 'canvas.gear.ref.rootFilletRadius': 'Référence de rayon de congé de pied', 'canvas.gear.ref.crestForm': 'Référence de forme de tête', 'canvas.gear.ref.crestRadius': 'Référence de rayon de tête', 'canvas.gear.ref.boreDiameter': 'Référence de diamètre d’alésage',
  'canvas.param.ngonSides': 'Côtés (3-50)', 'canvas.param.cornerRadius': 'Rayon de coin', 'canvas.param.chamfer': 'Chanfrein', 'canvas.param.ref.ngonSides': 'Référence du nombre de côtés du polygone', 'canvas.param.ref.roundRectCorner': 'Référence du rayon de coin du rectangle arrondi', 'canvas.param.ref.chamferRectCorner': 'Référence du coin du rectangle chanfreiné',
  'canvas.warning.selfIntersect': 'Ce profil s’auto-intersecte. Les résultats 3D/FAO peuvent être invalides.', 'canvas.warning.exceedsStock': 'Ce profil dépasse la limite du brut.',
  'canvas.axisLock.lock': 'Verrouiller', 'canvas.axisLock.lockX': 'Verrouiller X', 'canvas.axisLock.lockY': 'Verrouiller Y', 'canvas.axisLock.cycleAria': 'Cliquez pour parcourir le verrouillage d’axe (Alt)', 'canvas.axisLock.multiSelect': 'Multi', 'canvas.axisLock.multiSelectTitle': 'Activer/désactiver la sélection multiple', 'canvas.axisLock.multiSelectDisabledTitle': 'La sélection multiple est automatique pour Joindre et Découper',
  'canvas.preview.pendingRectangle': 'Rectangle en attente', 'canvas.preview.pendingTab': 'Attache en attente', 'canvas.preview.pendingClamp': 'Bride en attente', 'canvas.preview.pendingEllipse': 'Ellipse en attente', 'canvas.preview.pendingCircle': 'Cercle en attente', 'canvas.preview.pendingPolygon': 'Polygone en attente', 'canvas.preview.movePreview': 'Prévisualisation du déplacement', 'canvas.preview.copyPreview': 'Prévisualisation de la copie', 'canvas.preview.pastePreview': 'Prévisualisation du collage', 'canvas.preview.resizePreview': 'Prévisualisation du redimensionnement', 'canvas.preview.rotatePreview': 'Prévisualisation de la rotation', 'canvas.preview.mirrorPreview': 'Prévisualisation de la symétrie', 'canvas.preview.filletPreview': 'Prévisualisation du congé', 'canvas.preview.chamferPreview': 'Prévisualisation du chanfrein', 'canvas.preview.offsetInPreview': 'Prévisualisation du décalage intérieur', 'canvas.preview.offsetOutPreview': 'Prévisualisation du décalage extérieur',
}
