/**
 * Copyright 2026 Franja (Frank) Povazanj
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { dialogsEn } from '../en/dialogs'

/** French dialog catalog. */
export const dialogsFr: Record<keyof typeof dialogsEn, string> = {
  'dialogs.common.close': 'Fermer', 'dialogs.common.cancel': 'Annuler', 'dialogs.common.none': 'Aucune', 'dialogs.common.millimeter': 'Millimètre', 'dialogs.common.inch': 'Pouce',
  'dialogs.newProject.title': 'Nouveau projet', 'dialogs.newProject.projectName': 'Nom du projet', 'dialogs.newProject.template': 'Modèle', 'dialogs.newProject.templateBlankMetric': 'Métrique vierge', 'dialogs.newProject.templateBlankMetricMeta': 'Projet vide en millimètres.', 'dialogs.newProject.templateBlankImperial': 'Impérial vierge', 'dialogs.newProject.templateBlankImperialMeta': 'Projet vide en pouces.', 'dialogs.newProject.templateCurrentProject': 'Projet actuel', 'dialogs.newProject.templateCurrentProjectMeta': 'Utiliser les paramètres du projet ouvert comme modèle de départ.', 'dialogs.newProject.templateFile': 'Fichier modèle', 'dialogs.newProject.templateFileNoFile': 'Aucun fichier modèle chargé.', 'dialogs.newProject.templateFileParseError': 'Impossible d’analyser le fichier de projet modèle.', 'dialogs.newProject.templatePreview': 'Aperçu du modèle', 'dialogs.newProject.previewUnits': 'Unités', 'dialogs.newProject.previewStock': 'Brut', 'dialogs.newProject.previewFeatures': 'Entités', 'dialogs.newProject.previewTools': 'Outils', 'dialogs.newProject.previewOperations': 'Opérations', 'dialogs.newProject.previewMachine': 'Machine', 'dialogs.newProject.previewEmpty': 'Chargez un fichier de projet pour l’utiliser comme modèle.', 'dialogs.newProject.orOpenExample': 'Ou ouvrez un exemple', 'dialogs.newProject.createProject': 'Créer le projet',
  'dialogs.newProject.templateLabel.blankMetric': 'Métrique vierge', 'dialogs.newProject.templateLabel.blankImperial': 'Impérial vierge', 'dialogs.newProject.templateLabel.currentProject': 'Configuration du projet actuel : {name}', 'dialogs.newProject.templateLabel.fileSetup': 'Configuration du fichier modèle : {name}', 'dialogs.newProject.templateLabel.fileSetupFallback': 'Configuration du fichier modèle', 'dialogs.newProject.templateFileMetaSettings': '{name} (paramètres seulement)',
  'dialogs.importGeometry.title': 'Importer une géométrie', 'dialogs.importGeometry.sourceFile': 'Fichier source', 'dialogs.importGeometry.chooseFile': 'Choisir un SVG, DXF, STL, OBJ ou .camj', 'dialogs.importGeometry.chooseDifferentFile': 'Choisir un autre fichier', 'dialogs.importGeometry.noFileSelected': 'Aucun fichier sélectionné.', 'dialogs.importGeometry.settings': 'Paramètres', 'dialogs.importGeometry.format': 'Format', 'dialogs.importGeometry.sourceUnits': 'Unités source', 'dialogs.importGeometry.selectUnits': 'Sélectionner les unités', 'dialogs.importGeometry.unitsNotDetected': 'Unités non détectées — choisissez les unités source avant l’importation.', 'dialogs.importGeometry.camjImportNote': 'L’arrière-plan, la grille, les définitions de machine et les contraintes globales ne sont pas importés.', 'dialogs.importGeometry.importStock': 'Importer le brut depuis la source', 'dialogs.importGeometry.stockWillBeReplaced': 'Le brut et l’origine actuels seront remplacés.', 'dialogs.importGeometry.projectUnits': 'Unités du projet', 'dialogs.importGeometry.axisOrientation': 'Orientation des axes', 'dialogs.importGeometry.axisOriginal': 'Originale (Z vers le haut)', 'dialogs.importGeometry.axisSwapYZ': 'Inverser Y / Z (Y vers le haut)', 'dialogs.importGeometry.axisSwapXZ': 'Inverser X / Z', 'dialogs.importGeometry.axisSwapXY': 'Inverser X / Y', 'dialogs.importGeometry.silhouetteZSteps': 'Pas Z de la silhouette', 'dialogs.importGeometry.silhouetteAuto': 'Auto', 'dialogs.importGeometry.joinTolerance': 'Tolérance de jonction ({unit})', 'dialogs.importGeometry.crossLayerJoin': 'Jonction intercalques', 'dialogs.importGeometry.layers': 'Calques', 'dialogs.importGeometry.folders': 'Dossiers', 'dialogs.importGeometry.selectAll': 'Tout sélectionner', 'dialogs.importGeometry.deselectAll': 'Tout désélectionner', 'dialogs.importGeometry.selectAtLeastOne': 'Sélectionnez au moins un {type} à importer.', 'dialogs.importGeometry.folderNoun': 'dossier', 'dialogs.importGeometry.layerNoun': 'calque', 'dialogs.importGeometry.import': 'Importer',
  'dialogs.importGeometry.error.unsupportedFormat': 'Format d’importation non pris en charge. Utilisez .svg, .dxf, .stl, .obj ou .camj.', 'dialogs.importGeometry.error.noCamjFolders': 'Aucun dossier contenant des entités dans le fichier .camj sélectionné.', 'dialogs.importGeometry.error.inspectFailed': 'Impossible d’examiner le fichier de géométrie.', 'dialogs.importGeometry.error.chooseFile': 'Choisissez un fichier SVG, DXF, STL, OBJ ou .camj à importer.', 'dialogs.importGeometry.error.sourceUnits': 'Les unités source n’ont pas pu être détectées. Choisissez-les pour continuer.', 'dialogs.importGeometry.error.joinTolerance': 'La tolérance de jonction doit être un nombre non négatif.', 'dialogs.importGeometry.error.selectFolder': 'Sélectionnez au moins un dossier à importer, ou cochez « Importer le brut depuis la source ».', 'dialogs.importGeometry.error.noFeaturesImported': 'Aucune entité n’a été importée depuis les dossiers sélectionnés.', 'dialogs.importGeometry.error.noGeometryFound': 'Aucune géométrie importable dans le fichier sélectionné.', 'dialogs.importGeometry.error.importFailed': 'Impossible d’importer le fichier de géométrie.',
  'dialogs.importGeometry.processingModel': 'Traitement du modèle', 'dialogs.importGeometry.preparingImport': 'Préparation de l’importation', 'dialogs.importGeometry.mergingFolders': 'Fusion des dossiers', 'dialogs.importGeometry.importingGeometry': 'Importation de la géométrie', 'dialogs.importGeometry.formatLabel.camj': 'Projet PureCutCNC', 'dialogs.importGeometry.formatLabel.unknown': 'Inconnu', 'dialogs.importGeometry.importedFeaturesWarnings.one': '{count} entité importée avec avertissements :\n\n{warnings}', 'dialogs.importGeometry.importedFeaturesWarnings.other': '{count} entités importées avec avertissements :\n\n{warnings}',
  'dialogs.importGeometry.mode.geometryMode': 'Mode de géométrie', 'dialogs.importGeometry.mode.auto': 'Auto', 'dialogs.importGeometry.mode.paths': 'Chemins', 'dialogs.importGeometry.mode.solidRegions': 'Régions solides', 'dialogs.importGeometry.mode.explain.autoSvg': 'Auto : géométrie avec trait seul → Lignes ; formes fermées remplies → solides tenant compte de l’imbrication.', 'dialogs.importGeometry.mode.explain.autoDxf': 'Auto : profils fermés → solides tenant compte de l’imbrication. Utilisez Chemins pour importer seulement les lignes.', 'dialogs.importGeometry.mode.explain.paths': 'Chemins : tous les profils → Lignes (aucune entité solide).', 'dialogs.importGeometry.mode.explain.solidRegions': 'Régions solides : profils fermés → solides Ajouter/Soustraire tenant compte de l’imbrication.', 'dialogs.importGeometry.mode.analysing': 'Analyse de la géométrie…', 'dialogs.importGeometry.mode.importSummary': 'Résumé de l’importation', 'dialogs.importGeometry.mode.totalImportable': 'Total importable', 'dialogs.importGeometry.mode.openLines': 'Lignes ouvertes', 'dialogs.importGeometry.mode.closedLines': 'Lignes fermées', 'dialogs.importGeometry.mode.addSolid': 'Ajouter (solide)', 'dialogs.importGeometry.mode.subtractSolid': 'Soustraire (solide)',
  'dialogs.textTool.title': 'Ajouter du texte', 'dialogs.textTool.text': 'Texte', 'dialogs.textTool.fontStyle': 'Style de police', 'dialogs.textTool.font': 'Police', 'dialogs.textTool.height': 'Hauteur', 'dialogs.textTool.operation': 'Opération', 'dialogs.textTool.style.skeleton': 'Squelette', 'dialogs.textTool.style.outline': 'Contour', 'dialogs.textTool.operation.subtract': 'Soustraire', 'dialogs.textTool.operation.add': 'Ajouter', 'dialogs.textTool.helpText': 'Texte sur une seule ligne pour le moment. Le texte de contour génère des entités fermées ; le texte squelette génère des chemins de gravure ouverts.', 'dialogs.textTool.placeText': 'Placer le texte',
  'dialogs.unitConversion.eyebrow': 'Échelle du projet', 'dialogs.unitConversion.title': 'Modifier les unités du projet ?', 'dialogs.unitConversion.ariaChanging': 'Changement de {from} vers {to}', 'dialogs.unitConversion.intro': 'Choisissez si les mesures existantes doivent garder leur taille physique ou leurs nombres écrits.', 'dialogs.unitConversion.convertHeading': 'Convertir les valeurs', 'dialogs.unitConversion.convertBadge': 'Recommandé', 'dialogs.unitConversion.convertDescription': 'Préserve la taille physique du dessin, du brut, des cotes et des valeurs d’usinage.', 'dialogs.unitConversion.convertExample': '{from} devient {to}', 'dialogs.unitConversion.keepHeading': 'Conserver les valeurs numériques', 'dialogs.unitConversion.keepDescription': 'Réinterprète chaque nombre dans les nouvelles unités et modifie l’échelle physique du projet.', 'dialogs.unitConversion.keepExample': '{from} devient {to}',
  'dialogs.exampleProject.loading': 'Chargement des exemples…', 'dialogs.exampleProject.noExamples': 'Aucun exemple disponible.', 'dialogs.exampleProject.opening': 'Ouverture…', 'dialogs.exampleProject.errorLoad': 'Impossible de charger les exemples.', 'dialogs.exampleProject.errorOpen': 'Impossible d’ouvrir l’exemple.',
  'dialogs.export.title': 'Exporter le G-code', 'dialogs.export.machine': 'Machine', 'dialogs.export.machineNone': 'Aucune sélectionnée', 'dialogs.export.change': 'Modifier', 'dialogs.export.origin': 'Origine', 'dialogs.export.originDescription': 'L’exportation utilise l’origine actuelle du projet comme X0 Y0 Z0 machine.', 'dialogs.export.originNote': 'Modifiez l’origine dans l’esquisse ou l’arborescence du projet pour changer le zéro de travail utilisé à l’exportation.', 'dialogs.export.projectUnits': 'Unités du projet', 'dialogs.export.operations': 'Opérations', 'dialogs.export.noOperations': 'Aucune opération à exporter. Ajoutez-en une dans le panneau Opérations.', 'dialogs.export.options': 'Options', 'dialogs.export.emitToolChanges': 'Émettre les changements d’outil (M6)', 'dialogs.export.emitCoolant': 'Émettre les commandes de liquide de refroidissement', 'dialogs.export.warnings': 'Avertissements', 'dialogs.export.preview': 'Aperçu (30 premières lignes)', 'dialogs.export.previewPlaceholder': 'Sélectionnez une machine dans les paramètres du projet pour générer l’aperçu G-code.', 'dialogs.export.previewTruncated': '…', 'dialogs.export.movesLines': '{moves} mouvements, {lines} lignes au total', 'dialogs.export.warning.noOperations': 'Aucune opération sélectionnée. Cochez au moins une opération à exporter.', 'dialogs.export.warning.noMachine': 'Aucune machine sélectionnée. Choisissez-en une dans les paramètres du projet avant l’exportation.', 'dialogs.export.export': 'Exporter {ext}', 'dialogs.export.operationDisabled': 'L’opération est désactivée', 'dialogs.export.noToolAssigned': 'Aucun outil affecté',
  'dialogs.modelExport.title': 'Exporter le modèle', 'dialogs.modelExport.format': 'Format', 'dialogs.modelExport.fileName': 'Nom du fichier', 'dialogs.modelExport.fileNameHint': 'Enregistré sous {filename}. L’emplacement sera choisi dans la boîte de dialogue suivante.', 'dialogs.modelExport.curveQuality': 'Qualité des courbes', 'dialogs.modelExport.curveQualityHint': 'Détermine la finesse de la tessellation des arcs et courbes de Bézier. Plus fin = plus de triangles, courbes plus lisses.', 'dialogs.modelExport.summary': 'Résumé', 'dialogs.modelExport.exportedSize': 'Taille exportée : {width} × {height} {unit} à 1:1', 'dialogs.modelExport.exportedSizeNote': 'Chemins vectoriels modifiables ; les entités masquées sont exclues et les cotes suivent le réglage d’esquisse.', 'dialogs.modelExport.assembling': 'Assemblage du maillage…', 'dialogs.modelExport.triangles': '{count} triangles', 'dialogs.modelExport.estimatedSize': 'Taille de fichier estimée : {size}', 'dialogs.modelExport.warnings': 'Avertissements', 'dialogs.modelExport.error': 'Erreur', 'dialogs.modelExport.noGeometry': 'Aucune géométrie solide à exporter — ajoutez d’abord des entités visibles.', 'dialogs.modelExport.exporting': 'Exportation…', 'dialogs.modelExport.export': 'Exporter .{ext}',
  'dialogs.modelExport.stlEncoding': 'Encodage STL', 'dialogs.modelExport.stlBinary': 'Binaire (recommandé — plus petit, plus rapide)', 'dialogs.modelExport.stlAscii': 'ASCII (lisible par un humain)', 'dialogs.modelExport.contents': 'Contenu', 'dialogs.modelExport.includeImportedMeshes': 'Inclure les maillages importés', 'dialogs.modelExport.svgArea': 'Zone d’exportation', 'dialogs.modelExport.svgContent': 'Contenu', 'dialogs.modelExport.svgContent.tabs': 'Attaches', 'dialogs.modelExport.svgContent.clamps': 'Brides', 'dialogs.modelExport.svgContent.featureLabels': 'Étiquettes des entités', 'dialogs.modelExport.svgContent.grid': 'Grille', 'dialogs.modelExport.svgContent.color': 'Couleur', 'dialogs.modelExport.svgContent.monochrome': 'Monochrome', 'dialogs.modelExport.curveQuality.coarse': 'Grossière (10° — correspond à la vue 3D)', 'dialogs.modelExport.curveQuality.normal': 'Normale (5°)', 'dialogs.modelExport.curveQuality.fine': 'Fine (2°)', 'dialogs.modelExport.curveQuality.veryFine': 'Très fine (1°)',
  'dialogs.printDesign.title': 'Imprimer le dessin', 'dialogs.printDesign.paper': 'Papier', 'dialogs.printDesign.customSize': 'Taille personnalisée', 'dialogs.printDesign.size': 'Taille ({unit})', 'dialogs.printDesign.customPaperWidth': 'Largeur de papier personnalisée ({unit})', 'dialogs.printDesign.customPaperHeight': 'Hauteur de papier personnalisée ({unit})', 'dialogs.printDesign.portrait': 'Portrait', 'dialogs.printDesign.landscape': 'Paysage', 'dialogs.printDesign.margins': 'Marges ({unit})', 'dialogs.printDesign.printArea': 'Zone d’impression', 'dialogs.printDesign.printArea.visible': 'Limites visibles du dessin', 'dialogs.printDesign.printArea.stock': 'Limites du brut', 'dialogs.printDesign.printArea.view': 'Vue d’esquisse actuelle', 'dialogs.printDesign.currentViewUnavailable': 'La vue d’esquisse actuelle est disponible lorsque le canevas d’esquisse est ouvert.', 'dialogs.printDesign.scale': 'Échelle', 'dialogs.printDesign.fitToPage': 'Ajuster à la page', 'dialogs.printDesign.actualSize': 'Taille réelle (1:1)', 'dialogs.printDesign.custom': 'Personnalisée', 'dialogs.printDesign.customScaleAria': 'Échelle personnalisée (ratio, pourcentage ou facteur)', 'dialogs.printDesign.offsetXY': 'Décalage X / Y ({unit})', 'dialogs.printDesign.offsetX': 'Décalage horizontal ({unit})', 'dialogs.printDesign.offsetY': 'Décalage vertical ({unit})', 'dialogs.printDesign.content': 'Contenu', 'dialogs.printDesign.content.grid': 'Grille', 'dialogs.printDesign.content.backdrop': 'Image d’arrière-plan', 'dialogs.printDesign.content.featureLabels': 'Étiquettes des entités', 'dialogs.printDesign.content.tabs': 'Attaches', 'dialogs.printDesign.content.clamps': 'Brides', 'dialogs.printDesign.content.toolpaths': 'Superpositions de parcours d’outil', 'dialogs.printDesign.content.titleBlock': 'Cartouche', 'dialogs.printDesign.content.color': 'Couleur', 'dialogs.printDesign.content.monochrome': 'Monochrome', 'dialogs.printDesign.printedSize': 'Taille imprimée : {width} × {height} {unit} à {scale}', 'dialogs.printDesign.close': 'Fermer', 'dialogs.printDesign.print': 'Imprimer…',
  'dialogs.printDesign.warning.customScale': 'Échelle personnalisée non reconnue — saisissez un ratio comme 1:2, un pourcentage comme 50 % ou un facteur comme 0,5.', 'dialogs.printDesign.warning.clipped': 'Le dessin est rogné sur ce papier à l’échelle sélectionnée. Ajustez à la page, réduisez l’échelle ou choisissez un papier plus grand.', 'dialogs.printDesign.noTabs': 'Aucune attache dans ce projet', 'dialogs.printDesign.noClamps': 'Aucune bride dans ce projet', 'dialogs.printDesign.noToolpaths': 'Aucun parcours d’outil n’est visible dans la vue d’esquisse', 'dialogs.printDesign.noBackdrop': 'Aucune image d’arrière-plan dans ce projet',
  'dialogs.machineEditor.title': 'Modifier la machine : {name}', 'dialogs.machineEditor.general': 'Général', 'dialogs.machineEditor.name': 'Nom', 'dialogs.machineEditor.fileExtension': 'Extension de fichier', 'dialogs.machineEditor.mmCommand': 'Unités — commande mm', 'dialogs.machineEditor.inchCommand': 'Unités — commande pouce', 'dialogs.machineEditor.program': 'Programme', 'dialogs.machineEditor.header': 'En-tête', 'dialogs.machineEditor.operationHeader': 'En-tête d’opération', 'dialogs.machineEditor.footer': 'Pied de page', 'dialogs.machineEditor.toolChange': 'Changement d’outil', 'dialogs.machineEditor.toolChangeCommands': 'Commandes', 'dialogs.machineEditor.coolant': 'Liquide de refroidissement', 'dialogs.machineEditor.floodOn': 'Arrosage activé', 'dialogs.machineEditor.mistOn': 'Brumisation activée', 'dialogs.machineEditor.coolantOff': 'Liquide de refroidissement désactivé', 'dialogs.machineEditor.advanced': 'Avancé (JSON brut)', 'dialogs.machineEditor.variablesReference': 'Référence des variables', 'dialogs.machineEditor.save': 'Enregistrer', 'dialogs.machineEditor.invalidJson': 'Syntaxe JSON non valide',
  'dialogs.machineManager.title': 'Gérer les machines', 'dialogs.machineManager.builtin': 'Intégrée', 'dialogs.machineManager.custom': 'Personnalisée', 'dialogs.machineManager.active': 'Active', 'dialogs.machineManager.fileExtension': 'Extension de fichier', 'dialogs.machineManager.description': 'Description', 'dialogs.machineManager.vendor': 'Fabricant', 'dialogs.machineManager.builtinHint': 'Les définitions intégrées sont en lecture seule. Dupliquez-en une pour créer une copie modifiable.', 'dialogs.machineManager.useThisMachine': 'Utiliser cette machine', 'dialogs.machineManager.edit': 'Modifier', 'dialogs.machineManager.duplicateToEdit': 'Dupliquer pour modifier', 'dialogs.machineManager.duplicate': 'Dupliquer', 'dialogs.machineManager.importMachine': 'Importer une machine', 'dialogs.machineManager.exportMachine': 'Exporter une machine', 'dialogs.machineManager.removeMachine': 'Supprimer la machine', 'dialogs.machineManager.done': 'Terminé', 'dialogs.machineManager.empty': 'Aucune définition de machine. Importez-en une pour commencer.', 'dialogs.machineManager.emptyDetail': 'Sélectionnez une machine dans la liste ou importez-en une.', 'dialogs.machineManager.invalidImport': 'JSON de définition de machine non valide : {message}',
}
