/**
 * Copyright 2026 Franja (Frank) Povazanj
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { featureTreeEn } from '../en/featureTree'

/** French feature-tree catalog. */
export const featureTreeFr: Record<keyof typeof featureTreeEn, string> = {
  'featureTree.tree.project': 'Projet', 'featureTree.tree.grid': 'Grille', 'featureTree.tree.stock': 'Brut', 'featureTree.tree.origin': 'Origine', 'featureTree.tree.backdrop': 'Arrière-plan', 'featureTree.tree.features': 'Entités', 'featureTree.tree.regions': 'Régions', 'featureTree.tree.construction': 'Construction', 'featureTree.tree.tabs': 'Attaches', 'featureTree.tree.clamps': 'Brides',
  'featureTree.tree.branch.project': 'proj', 'featureTree.tree.branch.grid': 'grille', 'featureTree.tree.branch.stock': 'racine', 'featureTree.tree.branch.origin': 'orig', 'featureTree.tree.branch.backdrop': 'arr', 'featureTree.tree.branch.features': 'ent', 'featureTree.tree.branch.regions': 'rég', 'featureTree.tree.branch.construction': 'cons', 'featureTree.tree.branch.tabs': 'racine', 'featureTree.tree.branch.clamps': 'bride', 'featureTree.tree.branch.tab': 'nœud', 'featureTree.tree.branch.clamp': 'nœud', 'featureTree.tree.branch.feature': 'nœud',
  'featureTree.tree.empty.features': 'Aucun nœud d’entité.', 'featureTree.tree.empty.regions': 'Aucune région.', 'featureTree.tree.empty.construction': 'Aucune géométrie de construction.', 'featureTree.tree.empty.tabs': 'Aucune attache.', 'featureTree.tree.empty.clamps': 'Aucune bride.', 'featureTree.tree.empty.folder': 'Dossier vide.',
  'featureTree.tree.warning.firstFeaturePrefix': '⚠ La première entité 2,5D doit être ', 'featureTree.tree.warning.firstFeatureSuffix': '. Le modèle 3D ne sera pas construit avant correction.',
  'featureTree.treeRow.folder.expand': 'Développer le dossier', 'featureTree.treeRow.folder.collapse': 'Réduire le dossier', 'featureTree.treeRow.grip.dragToReorder': 'Glisser pour réorganiser',
  'featureTree.treeRow.badge.region.include': 'inclure', 'featureTree.treeRow.badge.region.exclude': 'exclure', 'featureTree.treeRow.badge.region.includeTooltip': 'Inclure la région — ajoute cette zone au masque de région actif.', 'featureTree.treeRow.badge.region.excludeTooltip': 'Exclure la région — soustrait cette zone du masque de région actif.', 'featureTree.treeRow.badge.construction.label': 'réf', 'featureTree.treeRow.badge.construction.tooltip': 'Construction — géométrie de référence de l’esquisse. Accrochage, symétrie et cotation possibles ; jamais usinée.', 'featureTree.treeRow.badge.linked': 'Liée — {count} instances partagent cette définition',
  'featureTree.treeRow.showAll.features': 'Afficher toutes les entités', 'featureTree.treeRow.showAll.regions': 'Afficher toutes les régions', 'featureTree.treeRow.showAll.construction': 'Afficher toute la construction', 'featureTree.treeRow.showAll.tabs': 'Afficher toutes les attaches', 'featureTree.treeRow.showAll.clamps': 'Afficher toutes les brides', 'featureTree.treeRow.hideAll.features': 'Masquer toutes les entités', 'featureTree.treeRow.hideAll.regions': 'Masquer toutes les régions', 'featureTree.treeRow.hideAll.construction': 'Masquer toute la construction', 'featureTree.treeRow.hideAll.tabs': 'Masquer toutes les attaches', 'featureTree.treeRow.hideAll.clamps': 'Masquer toutes les brides',
  'featureTree.treeRow.addFolder.default': 'Ajouter un dossier', 'featureTree.treeRow.addFolder.regions': 'Ajouter un dossier de régions', 'featureTree.treeRow.addFolder.construction': 'Ajouter un dossier de construction', 'featureTree.treeRow.addEntry.tab': 'Ajouter une attache', 'featureTree.treeRow.addEntry.clamp': 'Ajouter une bride',
  'featureTree.treeRow.operation.lineClosedTooltip': 'Ligne — chemin fermé utilisable par les opérations de gravure, profil et gravure en V', 'featureTree.treeRow.operation.lineOpenTooltip': 'Ligne — profil ouvert (Ligne ↔ Construction seulement)', 'featureTree.treeRow.operation.modelTooltip': 'Modèle — objet 3D importé (verrouillé)', 'featureTree.treeRow.operation.addFirstSolidTooltip': 'Ajouter — premier solide (Soustraire indisponible ; passez à un rôle non solide pour déverrouiller)', 'featureTree.treeRow.operation.addTooltip': 'L’entité ajoute de la matière', 'featureTree.treeRow.operation.subtractTooltip': 'L’entité soustrait de la matière', 'featureTree.treeRow.operation.constructionTooltip': 'Construction — géométrie de référence d’esquisse (jamais usinée)', 'featureTree.treeRow.operation.regionTooltip': 'Région — limite les zones usinables (jamais usinée)', 'featureTree.treeRow.operation.modelLockedAria': 'Modèle — opération verrouillée', 'featureTree.treeRow.operation.changeAria': 'Modifier l’opération',
  'featureTree.operation.add': 'Ajouter', 'featureTree.operation.subtract': 'Soustraire', 'featureTree.operation.line': 'Ligne', 'featureTree.operation.region': 'Masque de région', 'featureTree.operation.construction': 'Construction',
  'featureTree.treeRow.operation.menuLineOpenTooltip': 'Ligne — chemin ouvert usiné par les opérations de gravure', 'featureTree.treeRow.operation.menuAddTooltip': 'Ajouter — l’entité ajoute de la matière', 'featureTree.treeRow.operation.menuSubtractTooltip': 'Soustraire — l’entité enlève de la matière', 'featureTree.treeRow.operation.menuSubtractDisabledTooltip': 'Soustraire indisponible — le premier solide doit être Ajouter ou un rôle non solide', 'featureTree.treeRow.operation.menuLineClosedTooltip': 'Ligne — chemin fermé usiné par les opérations de gravure/contournage', 'featureTree.treeRow.operation.menuRegionTooltip': 'Masque de région — l’entité filtre les opérations d’usinage', 'featureTree.treeRow.operation.menuConstructionTooltip': 'Construction — géométrie de référence d’esquisse, jamais usinée',
  'featureTree.treeRow.selectAllInFolder': 'Sélectionner toutes les entités du dossier', 'featureTree.treeRow.group': 'Grouper les entités', 'featureTree.treeRow.ungroup': 'Dégrouper les entités', 'featureTree.treeRow.editSketch': 'Modifier l’esquisse', 'featureTree.treeRow.moreActions': 'Autres actions', 'featureTree.treeRow.hideEntry': 'Masquer l’entrée', 'featureTree.treeRow.showEntry': 'Afficher l’entrée',
  'featureTree.properties.name': 'Nom', 'featureTree.properties.units': 'Unités', 'featureTree.properties.width': 'Largeur', 'featureTree.properties.height': 'Hauteur', 'featureTree.properties.thickness': 'Épaisseur', 'featureTree.properties.color': 'Couleur', 'featureTree.properties.visible': 'Visible', 'featureTree.properties.locked': 'Verrouillé', 'featureTree.properties.z': 'Z', 'featureTree.properties.zTop': 'Z haut', 'featureTree.properties.zBottom': 'Z bas', 'featureTree.properties.zRange': 'Plage Z', 'featureTree.properties.image': 'Image', 'featureTree.properties.opacity': 'Opacité', 'featureTree.properties.angle': 'Angle', 'featureTree.properties.folder': 'Dossier', 'featureTree.properties.folders': 'Dossiers', 'featureTree.properties.features': 'Entités', 'featureTree.properties.clamps': 'Brides', 'featureTree.properties.tabs': 'Attaches', 'featureTree.properties.operation': 'Opération', 'featureTree.properties.selection': 'Sélection', 'featureTree.properties.editSketch': 'Modifier l’esquisse', 'featureTree.properties.text': 'Texte', 'featureTree.properties.style': 'Style', 'featureTree.properties.font': 'Police', 'featureTree.properties.sourceFeature': 'Entité source', 'featureTree.properties.expanded': 'Développé',
  'featureTree.properties.safeZ': 'Z de sécurité', 'featureTree.properties.opClearZ': 'Z de dégagement de l’opération', 'featureTree.properties.clampClearXY': 'Dégagement XY des brides', 'featureTree.properties.clampClearZ': 'Dégagement Z des brides', 'featureTree.properties.machine': 'Machine', 'featureTree.properties.gridExtent': 'Étendue de la grille', 'featureTree.properties.majorLines': 'Lignes principales', 'featureTree.properties.minorLines': 'Lignes secondaires', 'featureTree.properties.snapIncrement': 'Incrément d’accrochage', 'featureTree.properties.showFeatureInfo': 'Afficher les informations d’entité dans l’esquisse',
  'featureTree.properties.units.mm': 'Millimètres', 'featureTree.properties.units.inch': 'Pouces', 'featureTree.properties.machine.none': 'Aucune', 'featureTree.properties.machine.refresh': 'Actualiser les définitions de machine', 'featureTree.properties.machine.manage': 'Gérer les machines…', 'featureTree.properties.machine.builtin': 'Intégrée', 'featureTree.properties.machine.custom': 'Personnalisée', 'featureTree.properties.machine.duplicateHint': 'dupliquer pour modifier',
  'featureTree.properties.origin.placeOrigin': 'Placer l’origine', 'featureTree.properties.origin.presets': 'Préréglages', 'featureTree.properties.origin.topLeft': 'En haut à gauche', 'featureTree.properties.origin.centerTop': 'Centré en haut', 'featureTree.properties.origin.bottomLeft': 'En bas à gauche',
  'featureTree.properties.stock.editSketch': 'Modifier l’esquisse', 'featureTree.properties.stock.resetToRect': 'Réinitialiser en rectangle', 'featureTree.properties.stock.nameDisabled': 'Brut',
  'featureTree.properties.backdrop.noImage': 'Aucune image chargée', 'featureTree.properties.backdrop.loadImage': 'Charger une image', 'featureTree.properties.backdrop.replaceImage': 'Remplacer l’image', 'featureTree.properties.backdrop.loading': 'Chargement de l’image…', 'featureTree.properties.backdrop.move': 'Déplacer', 'featureTree.properties.backdrop.resize': 'Redimensionner', 'featureTree.properties.backdrop.rotate': 'Faire pivoter', 'featureTree.properties.backdrop.delete': 'Supprimer', 'featureTree.properties.backdrop.decoding': 'Décodage de l’image d’arrière-plan…', 'featureTree.properties.backdrop.mustBeImage': 'L’arrière-plan doit être une image PNG ou JPEG.', 'featureTree.properties.backdrop.readFailed': 'Impossible de lire l’image d’arrière-plan.', 'featureTree.properties.backdrop.decodeFailed': 'Impossible de décoder l’image d’arrière-plan.',
  'featureTree.properties.shape': 'Forme', 'featureTree.properties.shapeShared.one': 'Forme (partagée avec {count} instance)', 'featureTree.properties.shapeShared.other': 'Forme (partagée avec {count} instances)', 'featureTree.properties.instance': 'Instance', 'featureTree.properties.expandText': 'Développer le texte en entités', 'featureTree.properties.makeUnique': 'Rendre unique', 'featureTree.properties.deleteFeature': 'Supprimer l’entité', 'featureTree.properties.deleteSelected': 'Supprimer la sélection', 'featureTree.properties.editSketchDisabledMulti': 'Désactivé pour la sélection multiple',
  'featureTree.properties.multi.group': 'Grouper', 'featureTree.properties.multi.ungroup': 'Dégrouper', 'featureTree.properties.multi.deleteGroup': 'Supprimer le groupe', 'featureTree.properties.multi.featuresCount': '{count} entités', 'featureTree.properties.multi.editSketchDisabled': 'Modifier l’esquisse n’est disponible que pour une seule entité', 'featureTree.properties.multi.openProfiles': 'Profils ouverts', 'featureTree.properties.multi.containsModel': 'Contient des entités de modèle', 'featureTree.properties.multi.modelLockedTooltip': 'Les entités de modèle ne peuvent pas modifier leur type d’opération ici',
  'featureTree.properties.select.mixedFolders': 'Dossiers mixtes', 'featureTree.properties.select.root': 'Racine', 'featureTree.properties.select.mixedOperations': 'Opérations mixtes', 'featureTree.properties.select.mixedModes': 'Modes mixtes', 'featureTree.properties.select.mixedValues': 'Valeurs mixtes',
  'featureTree.properties.operation.subtract': 'Soustraire', 'featureTree.properties.operation.add': 'Ajouter', 'featureTree.properties.operation.line': 'Ligne', 'featureTree.properties.operation.region': 'Masque de région', 'featureTree.properties.operation.construction': 'Construction', 'featureTree.properties.operation.model': 'Modèle', 'featureTree.properties.operation.modelLockedTooltip': 'Les entités de modèle sont des objets 3D importés et ne peuvent pas modifier leur type d’opération', 'featureTree.properties.maskMode': 'Mode de masque', 'featureTree.properties.maskMode.include': 'Inclure', 'featureTree.properties.maskMode.exclude': 'Exclure', 'featureTree.properties.text.skeleton': 'Squelette', 'featureTree.properties.text.outline': 'Contour',
  'featureTree.properties.z.notMachined': 'Non usiné', 'featureTree.properties.z.notMachinedTooltip': 'La géométrie de construction est une référence d’esquisse — elle n’a pas de profondeur d’usinage', 'featureTree.properties.z.followsStock': 'Suit le brut ({thickness} à 0)', 'featureTree.properties.z.followsStockTooltip': 'Les régions sont des filtres verticaux à travers le brut ; leur plage Z suit automatiquement le brut',
  'featureTree.properties.regionNote.badge': 'masque', 'featureTree.properties.regionNote.text': 'Une région est un filtre : elle limite les zones de coupe, ce n’est pas une forme à usiner.', 'featureTree.properties.constructionNote.badge': 'réf', 'featureTree.properties.constructionNote.text': 'La géométrie de construction est une référence d’esquisse : accrochage, symétrie et cotation sont possibles. Elle n’est jamais usinée.',
  'featureTree.properties.warning.selfIntersect': 'Ce profil s’auto-intersecte. Les résultats 3D/FAO peuvent être invalides.', 'featureTree.properties.warning.exceedsStock': 'Ce profil dépasse la limite du brut.',
  'featureTree.properties.constraints.title': 'Contraintes', 'featureTree.properties.constraints.delete': 'Supprimer la contrainte', 'featureTree.properties.constraints.type.intersect': 'intersection', 'featureTree.properties.constraints.type.perp': 'perp', 'featureTree.properties.constraints.type.line': 'ligne', 'featureTree.properties.constraints.type.midpt': 'milieu', 'featureTree.properties.constraints.type.center': 'centre', 'featureTree.properties.constraints.type.point': 'point', 'featureTree.properties.constraints.tooltip.distanceIntersection': 'Distance à l’intersection', 'featureTree.properties.constraints.tooltip.perpendicularSegment': 'Distance perpendiculaire au segment', 'featureTree.properties.constraints.tooltip.pointOnSegment': 'Distance au point du segment ({percent} %)', 'featureTree.properties.constraints.tooltip.segmentMidpoint': 'Distance au milieu du segment', 'featureTree.properties.constraints.tooltip.featureCenter': 'Distance au centre de l’entité', 'featureTree.properties.constraints.tooltip.distanceVertex': 'Distance au sommet', 'featureTree.properties.constraints.tooltip.invalid': 'Non valide', 'featureTree.properties.constraints.world': 'Monde',
  'featureTree.properties.empty': 'Sélectionnez Projet, Grille, Brut ou une entité de l’arborescence pour modifier ses propriétés.', 'featureTree.properties.name.grid': 'Grille', 'featureTree.properties.name.features': 'Entités', 'featureTree.properties.name.clamps': 'Brides', 'featureTree.properties.name.tabs': 'Attaches',
  'featureTree.properties.actions.addFolder': 'Ajouter un dossier', 'featureTree.properties.actions.addTab': 'Ajouter une attache', 'featureTree.properties.actions.addClamp': 'Ajouter une bride', 'featureTree.properties.actions.deleteFolder': 'Supprimer le dossier', 'featureTree.properties.actions.deleteClamp': 'Supprimer la bride', 'featureTree.properties.actions.deleteTab': 'Supprimer l’attache',
  'featureTree.contextMenu.makeUnique': 'Rendre unique', 'featureTree.contextMenu.selectLinked': 'Sélectionner les instances liées', 'featureTree.contextMenu.createOperation': 'Créer une opération', 'featureTree.contextMenu.editSketch': 'Modifier l’esquisse', 'featureTree.contextMenu.addConstraint': 'Ajouter une contrainte', 'featureTree.contextMenu.copy': 'Copier', 'featureTree.contextMenu.copySelected': 'Copier la sélection', 'featureTree.contextMenu.copyGroup': 'Copier le groupe', 'featureTree.contextMenu.move': 'Déplacer', 'featureTree.contextMenu.moveSelected': 'Déplacer la sélection', 'featureTree.contextMenu.moveGroup': 'Déplacer le groupe', 'featureTree.contextMenu.resize': 'Redimensionner', 'featureTree.contextMenu.rotate': 'Faire pivoter', 'featureTree.contextMenu.mirror': 'Symétrie', 'featureTree.contextMenu.offset': 'Décalage', 'featureTree.contextMenu.addToFolder': 'Ajouter au dossier', 'featureTree.contextMenu.createNewFolder': 'Créer un nouveau…', 'featureTree.contextMenu.group': 'Grouper', 'featureTree.contextMenu.join': 'Joindre', 'featureTree.contextMenu.cut': 'Découper', 'featureTree.contextMenu.useAsStock': 'Utiliser comme brut', 'featureTree.contextMenu.delete': 'Supprimer', 'featureTree.contextMenu.deleteSelected': 'Supprimer la sélection', 'featureTree.contextMenu.deleteGroup': 'Supprimer le groupe',
  'featureTree.contextMenu.lockedTooltip': 'Les entités verrouillées ne peuvent pas être déplacées', 'featureTree.contextMenu.groupDisabledTooltip': 'Sélectionnez au moins deux entités à grouper', 'featureTree.contextMenu.sectionsMixedTooltip': 'Les entités, régions et constructions ne se groupent qu’avec leur propre type', 'featureTree.contextMenu.addToFolderMixedTooltip': 'Les entités, régions et constructions ont des dossiers séparés — sélectionnez un seul type', 'featureTree.contextMenu.joinDisabledTooltip': 'Sélectionnez au moins deux entités à joindre', 'featureTree.contextMenu.useAsStockDisabledTooltip': 'L’entité doit être une opération Ajouter avec un profil fermé',
  'featureTree.zRange.zTop': 'Z haut', 'featureTree.zRange.zBottom': 'Z bas', 'featureTree.zRange.handleTopAria': 'Poignée Z haut', 'featureTree.zRange.handleBottomAria': 'Poignée Z bas',
}
